test('error', () => {
	throw new Error();
});
